# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dc0c7b781b2372d0ec9cb13ef7d9eba3"
name = "store migrator pro"
handle = "store-migrator-pro"
application_url = "https://storemigrator-pro-production.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
scopes = "write_products,write_customers,write_orders,read_content,write_content,read_themes"
[auth]
redirect_urls = [
  "https://storemigrator-pro-production.up.railway.app/auth/callback",
  "https://storemigrator-pro-production.up.railway.app/auth/shopify/callback",
  "https://storemigrator-pro-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://storemigrator-pro-production.up.railway.app/webhooks/customers/redact"
  customer_data_request_url = "https://storemigrator-pro-production.up.railway.app/webhooks/customers/data_request"
  shop_deletion_url = "https://storemigrator-pro-production.up.railway.app/webhooks/shop/redact"

[pos]
embedded = false
